apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          command: ["serve", "-s", "build"]
          image: docker.io/nzorro/restaurant-app:v0.2
          # add resource requests
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: restaurant
          command: ["node", "backend/restaurantService/start.js"]
          image: docker.io/nzorro/restaurant-app:v0.2
          env:
            - name: STORAGE
              value: "mongo"
            - name: MONGODB_URI
              value: "mongodb://mongodb-svc:27017/restaurantdb"
          # add resource requests
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        - name: checkout
          command: ["node", "backend/checkoutService/start.js"]
          image: docker.io/nzorro/restaurant-app:v0.2
          env:
            - name: STORAGE
              value: "mongo"
            - name: MONGODB_URI
              value: "mongodb://mongodb-svc:27017/restaurantdb"          
          # add resource requests
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        - name: menu
          command: ["node", "backend/menuService/start.js"]
          image: docker.io/nzorro/restaurant-app:v0.2
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-svc:27017/restaurantdb"
          # add resource requests
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          args: ["--bind_ip", "0.0.0.0"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          # add resource requests
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"              
      volumes:
        - name: mongo-data
          emptyDir: {}
