apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
  labels:
    app: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: restaurant-app
        command: ['/usr/local/bin/serve', '-s', 'build']
        image: nzorro/restaurant-app:latest
      - name: restaurant-service
        command: ['/bin/sh','-c','cd restaurantService && /usr/local/bin/node ./start.js']
        image: nzorro/restaurant-app:latest
      - name: checkout
        command: ['/bin/sh','-c','cd checkoutService && /usr/local/bin/node ./start.js']
        image: nzorro/restaurant-app:latest
      - name: menu
        command: ['/bin/sh','-c','cd menuService && /usr/local/bin/node ./start.js']
        image: nzorro/restaurant-app:latest
      imagePullSecrets:
      - name: regcred

---
# Service for the restaurant app
apiVersion: v1
kind: Service
metadata:
  name: restaurant-app-svc
spec:
  selector:
    app: restaurant-app
  ports:
  - name: main
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: restaurant-service
    protocol: TCP
    port: 3001
    targetPort: 3001
  - name: checkout-service
    protocol: TCP
    port: 3002
    targetPort: 3002
  - name: menu-service
    protocol: TCP
    port: 3003
    targetPort: 3003
  type: LoadBalancer
