apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
  labels:
    app: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: restaurant-app
        image: nzorro/restaurant-app:latest
      imagePullSecrets:
      - name: regcred

---
# Service for the restaurant app
apiVersion: v1
kind: Service
metadata:
  name: restaurant-app-svc
spec:
  selector:
    app: restaurant-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer